[package]
name = "flowclicker"
version = "1.5.0"
description = "Cross-platform physical mouse flow recorder and player"
authors = ["FlowClicker contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
enigo = "0.6.1"
rdev = "0.5.3"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
