const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));

export const editorRowsHtml = (actions = [], highlightedIds = []) => {
  const highlighted = new Set(highlightedIds);
  return actions.map((action, index) => {
  const click = action.type === 'click';
  const target = action.windowTitle || 'screen coordinates';
  return `<tr data-id="${escapeHtml(action.id)}"${click && highlighted.has(action.id) ? ' class="action-selected"' : ''}><td>${index + 1}</td><td><span class="action-type ${escapeHtml(action.type)}">${escapeHtml(action.type)}</span></td><td><input class="compact-input action-name" value="${escapeHtml(action.name)}"></td><td>${click ? `<input class="compact-input coord-x" type="number" value="${Number(action.screenX) || 0}">` : '—'}</td><td>${click ? `<input class="compact-input coord-y" type="number" value="${Number(action.screenY) || 0}">` : '—'}</td><td>${action.type === 'group' ? 'Group' : `<span class="delay-input"><input class="compact-input action-delay" type="number" value="${Number(action.delayMs) || 0}"><span>ms</span></span>`}</td><td class="target-cell">${click ? `<button class="icon-btn target-info" type="button" title="${escapeHtml(target)}" aria-label="Target: ${escapeHtml(target)}">ⓘ</button>` : '—'}</td><td class="row-actions"><div class="row-action-group"><button class="icon-btn row-action" data-action="move-up" type="button" title="Move up" aria-label="Move ${escapeHtml(action.name || action.type)} up"${index === 0 ? ' disabled' : ''}>↑</button><button class="icon-btn row-action" data-action="move-down" type="button" title="Move down" aria-label="Move ${escapeHtml(action.name || action.type)} down"${index === actions.length - 1 ? ' disabled' : ''}>↓</button><button class="icon-btn row-action" data-action="duplicate" type="button" title="Duplicate action" aria-label="Duplicate ${escapeHtml(action.name || action.type)}">⧉</button><button class="icon-btn row-action danger-ghost" data-action="delete" type="button" title="Delete action" aria-label="Delete ${escapeHtml(action.name || action.type)}">×</button></div></td></tr>`;
  }).join('');
};
